# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71d35af526a3e4d70aa45fe4ec72430fa1d56ce80e2f8b282d2c3973f36ee28f2cf55cc9db13070bd5f41135d4f88a91126670e846c646694900404fbe5063f3

test:
  secret_key_base: c9fd1d2756286222f9850b78e1f472bc895ca25970129de70fa819e86da3d0a8c0c5a13cbaa98e54f3360e316580105f18ce846219a1b70effc77d62d7bbf1c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
